version: '3.9'

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  worker:
    build:
      context: .
      dockerfile: WorkerService/Dockerfile
    environment:
      - Seq=http://seq:80
      - ObjectStore__Nodes__0=172.20.0.32:26379
      - ObjectStore__Nodes__1=172.20.0.33:26379
      - ObjectStore__Nodes__2=172.20.0.34:26379
      - ObjectStore__Extra=serviceName=mymaster,allowAdmin=true
    depends_on:
      - sentinel-1
      - sentinel-2
      - sentinel-3
      - redis-master
      - redis-replica-1
      - seq
    volumes:
      - ./locking.txt:/app/locking.txt
    networks:
      app_subnet:

  seq:
    image: 'datalust/seq:latest'
    container_name: seq
    hostname: seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    networks:
      app_subnet:

  redis-master:
    image: 'redis:7.0'
    container_name: 'redis-master'
    command: 'redis-server'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.30

  redis-replica-1:
    image: 'redis:7.0'
    container_name: 'redis-replica-1'
    command: 'redis-server --replicaof redis-master 6379'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.31

  sentinel-1:
    image: 'redis:7.0'
    container_name: 'sentinel-1'
    command: 'redis-server /etc/sentinel/sentinel-1.conf --sentinel'
    volumes:
      - './sentinelconf/:/etc/sentinel/'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.32

  sentinel-2:
    image: 'redis:7.0'
    container_name: 'sentinel-2'
    command: 'redis-server /etc/sentinel/sentinel-2.conf --sentinel'
    volumes:
      - './sentinelconf/:/etc/sentinel/'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.33

  sentinel-3:
    image: 'redis:7.0'
    container_name: 'sentinel-3'
    command: 'redis-server /etc/sentinel/sentinel-3.conf --sentinel'
    volumes:
      - './sentinelconf/:/etc/sentinel/'
    networks:
      app_subnet:
        ipv4_address: 172.20.0.34